---
clusterName: kube-stolon

registry: "leader.telekube.local:5000/"

debug: "false"

store:
  backend: etcd
  endpoints: "https://127.0.0.1:2379"
  caFile: /home/stolon/secrets/etcd/root.cert
  certFile: /home/stolon/secrets/etcd/etcd.cert
  key: /home/stolon/secrets/etcd/etcd.key

clusterSpec:
  requestTimeout: "60s"
  failInterval: "60s"
  maxStandbysPerSender: 5
  deadKeeperRemovalInterval: "48h"
  maxStandbyLage: 16777216
  usePgrewind: true
  initMode: "new"
  pgHBA:
    - hostssl all all 0.0.0.0/0 md5
    - hostssl all all ::0/0 md5
  pgParameters:
    idle_in_transaction_session_timeout: "10min"
    log_destination: "stderr"
    log_min_messages: "INFO"
    log_checkpoints: "on"
    log_min_duration_statement: "1s"
    log_lock_waits: "on"
    log_line_prefix: '%m [%p]: [%l-1] user=%u,db=%d '
    wal_keep_segments: "128"
    max_connections: "500"

sentinel:
  replicaCount: 3
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - stolon-sentinel
            topologyKey: kubernetes.io/hostname

keeper:
  nodeSelector:
    stolon-keeper: "yes"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values:
                  - stolon-keeper
          topologyKey: kubernetes.io/hostname
  initVolumeMounts:
    - name: stolon-secrets
      mountPath: /home/stolon/secrets
    - name: data
      mountPath: /stolon-data
    - name: cluster-ca
      mountPath: /etc/secrets/cluster-ca
    - name: cluster-default-ssl
      mountPath: /etc/secrets/cluster-default
    - name: etcd-secrets
      mountPath: /var/state
  volumeMounts:
    - name: stolon-secrets
      mountPath: /home/stolon/secrets
    - name: data
      mountPath: /stolon-data
    - name: cluster-ca
      mountPath: /etc/ssl/cluster-ca
    - name: cluster-default-ssl
      mountPath: /etc/ssl/cluster-default-ssl
  volumes:
    - name: stolon-secrets
      emptyDir: {}
    - name: etcd-secrets
      hostPath:
        path: /var/state
    - name: cluster-ca
      secret:
        secretName: cluster-ca
    - name: cluster-default-ssl
      secret:
        secretName: cluster-default-ssl

pgbouncer:
  replicaCount: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - stolon-pgbouncer
            topologyKey: kubernetes.io/hostname
