superuserPassword: passw0rd
replicationPassword: passw0rd

persistence:
  enabled: false

serviceMonitor:
  enabled: true

keeper:
  replicaCount: 3

clusterSpec:
  requestTimeout: "60s"
  failInterval: "60s"
  maxStandbyLag: 16
  usePgrewind: true
  maxStandbys: 5

pgParameters:
  max_connections: 500
  idle_in_transaction_session_timeout: "10min"
  log_destination: "stderr"
  log_min_messages: "INFO"
  log_checkpoints: "on"
  log_min_duration_statement: "1s"
  log_lock_waits: "on"
  log_line_prefix: '%m [%p]: [%l-1] user=%u,db=%d '
