apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "stolon.fullname" . }}-keeper
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "stolon.fullname" . }}-keeper-headless
  replicas: {{ .Values.keeper.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "stolon.name" . }}
      release: {{ .Release.Name }}
      component: stolon-keeper
  template:
    metadata:
      labels:
        app: {{ template "stolon.name" . }}
        release: {{ .Release.Name }}
        component: stolon-keeper
        stolon-cluster: {{ template "stolon.fullname" . }}
      annotations:
{{- with .Values.keeper.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
{{- if .Values.keeper.priorityClassName }}
      priorityClassName: "{{ .Values.keeper.priorityClassName }}"
{{- end }}
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
{{- if .Values.keeper.fsGroup }}
      securityContext:
        fsGroup: {{ .Values.keeper.fsGroup }}
{{- end }}
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
{{- end }}
      initContainers:
        - name: fix-permissions
          image: "{{ .Values.registry }}{{ .Values.commonImage.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.commonImage.pullPolicy }}
          command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/init-container.sh"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /stolon-data
            - name: stolon-secrets
              mountPath: /home/stolon/secrets
            - name: cluster-ca
              mountPath: /etc/secrets/cluster-ca
            - name: cluster-default-ssl
              mountPath: /etc/secrets/cluster-default
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.registry }}{{ .Values.image.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KEEPER
              value: "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: STKEEPER_UID
              value: "{{ .Values.keeper.uid_prefix }}${POD[-1]}"
            - name: STKEEPER_CLUSTER_NAME
              value: {{ template "stolon.clusterName" . }}
            - name: STKEEPER_STORE_BACKEND
              value: {{ .Values.store.backend | quote }}
            {{- if eq .Values.store.backend "kubernetes" }}
            - name: STKEEPER_KUBE_RESOURCE_KIND
              value: {{ .Values.store.kubeResourceKind  | quote }}
            {{- else }}
            - name: STKEEPER_STORE_ENDPOINTS
              value: {{ .Values.store.endpoints | quote }}
            {{- end }}
            - name: STKEEPER_PG_REPL_USERNAME
              value: {{ .Values.replicationUsername | quote}}
{{ if empty .Values.replicationPassword }}
            - name: STKEEPER_PG_REPL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "stolon.fullname" . }}
                  key: "pg_repl_password"
{{ else }}
              value: {{ .Values.replicationPassword | quote}}
{{ end }}
            - name: STKEEPER_PG_SU_USERNAME
              value: {{ .Values.superuserUsername | quote}}
{{ if empty .Values.superuserPassword }}
            - name: STKEEPER_PG_SU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "stolon.fullname" . }}
                  key: "password"
{{ else }}
              value: {{ .Values.superuserPassword | quote}}
{{ end }}
            - name: STKEEPER_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:{{ .Values.ports.metrics.containerPort }}"
            - name: STKEEPER_LOG_LEVEL
              value: {{ .Values.logLevel | quote}}
{{- if .Values.keeper.extraEnv }}
{{ toYaml .Values.keeper.extraEnv | indent 12 }}
{{- end }}
          ports:
{{- range $key, $value := .Values.ports }}
            - name: {{ $key }}
{{ toYaml $value | indent 14 }}
{{- end }}
          resources:
{{ toYaml .Values.keeper.resources | indent 12 }}
          volumeMounts:
          - name: data
            mountPath: /stolon-data
{{- if .Values.tls.enabled }}
          - name: stolon-secrets
            mountPath: /home/stolon/secrets
{{- end }}
{{- range $key, $value := .Values.keeper.volumeMounts }}
          - name: {{ $key }}
{{ toYaml $value | indent 12 }}
{{- end }}
{{- if .Values.keeper.hooks.failKeeper.enabled }}
          - name: config
            mountPath: /pre-stop-hook.sh
            subPath: pre-stop-hook.sh
{{- end }}
{{- if .Values.nodePostStartScript }}
          - name: config
            mountPath: /postStartScript.sh
            subPath: postStartScript.sh
{{- end }}
          lifecycle:
{{- if .Values.keeper.hooks.failKeeper.enabled }}
            preStop:
              exec:
                command: ["/bin/bash", "-e", "/pre-stop-hook.sh"]
{{- end }}
{{- if .Values.nodePostStartScript }}
            postStart:
              exec:
                command: ["/bin/bash", "-e", "/postStartScript.sh"]
{{- end }}
{{- with .Values.keeper.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.keeper.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.keeper.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      volumes:
{{- if .Values.tls.enabled }}
        - name: cluster-ca
          secret:
            defaultMode: 0600
            secretName: {{ .Values.tls.caSecret }}
        - name: cluster-default-ssl
          secret:
            defaultMode: 0600
            secretName: {{ .Values.tls.defaultSslSecret }}
{{ end }}
        - name: config
          configMap:
            name: {{ template "stolon.fullname" . }}
{{- range $key, $value := .Values.keeper.volumes }}
        - name: {{ $key }}
{{ toYaml $value | indent 10 }}
{{- end }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
  {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
  {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClassName }}
    {{- if (eq "-" .Values.persistence.storageClassName) }}
        storageClassName: ""
    {{- else }}
        storageClassName: "{{ .Values.persistence.storageClassName }}"
    {{- end }}
  {{- end }}
{{- else }}
        - name: data
          hostPath:
            path: {{ template "stolon.keeperDataPath" . }}
{{- end }}
